# Generated by Django 5.0.7 on 2024-07-21 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialname',
            name='position',
            field=models.CharField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
